name: btc_address_validate
version: 1.0.0
description: A minimal library to validate Bitcoin mainnet and testnet addresses
author: Dominik Spicher <dominikspicher@gmail.com>
homepage: https://github.com/dspicher/btc_address_validate

environment:
    sdk: ">=2.3.0 <3.0.0"

dependencies:
    bech32: ^0.1.2
    base58check: ^1.0.1
    equatable: ^2.0.0-nullsafety.3

dependency_overrides:
    # Pending PR: https://github.com/dartcoin/base58check/pull/2
    base58check:
        git:
            url: https://github.com/bottlepay/base58check.git

# NOTE: waiting for bech32 to migrate to null safety
# at this PR: https://github.com/haarts/bech32/pull/3

dev_dependencies:
    test: ^1.16.2


